BillsApplication/Controllers/BillsController.cs
using BillsApplication.Models;
using BillsApplicationDomain;
using BillsApplicationDomain.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BillsApplication.Controllers
{
    //public class BillController : Controller Replaced due to Error Handling being done through new BillBaseController which inherits from Controller
    public class BillController : BillBaseController
    {
        private IBillService _service;

        public BillController(IBillService service)
        {
            _service = service;
        }

        //
        // GET: /Bills/
        // 2nd Way to handle errors using attributes 3rd Way uses Webconfig
        //[HandleError(ExceptionType=typeof("What Type Of Exception =>" NotImplementedException), "What View shoudl be Used if blank goes to View/Shared/Error.cshtml =>" View="NotImplemented"]
        [HandleError(ExceptionType=typeof(NotImplementedException), View="NotImplemented")]
        public ActionResult Index()
        {
            return View(_service.GetBills());
        }

        [HttpGet]
        public PartialViewResult Create()
        {
            return PartialView("_Create", new Bill()); 
        }

        [HttpPost]
        public ActionResult Create(Bill model)
        {
            if (ModelState.IsValid)
            {
                _service.Add(model);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var bill = _service.GetBillById(id);
            if (bill == null) throw new Exception("Could not find Bill");

            return View("Edit", bill);
        }

        [HttpPost]
        public ActionResult Edit(Bill model)
        {
            
            if (ModelState.IsValid)
            {
                _service.Update(model);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var bill = _service.GetBillById(id);
            if (bill == null) throw new Exception("Bill not found");

            return View(bill);
        }

        [HttpGet]
        public ActionResult DetailsByName(string billName)
        {
            var bill = _service.GetBillByName(billName);
            if (bill == null) throw new Exception("Bill not found");

            return View("Details", bill);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            _service.DeleteBillById(id);
            
            return RedirectToAction("Index");
        }

        // 1 way to override the OnException Error Handling output using Reflection this can be done on every controller or in a Bass (BillsBaseController)
        protected override void OnException(ExceptionContext filterContext)
        {
            if (filterContext.Exception is InvalidOperationException)
            {
                string controllerName = filterContext.RouteData.GetRequiredString("controller");
                string actionName = filterContext.RouteData.GetRequiredString("action");
                var model = new HandleErrorInfo(filterContext.Exception, controllerName, actionName);
                var result = new ViewResult
                {
                    ViewName = "Error",
                    ViewData = new ViewDataDictionary<HandleErrorInfo>(model),
                    TempData = filterContext.Controller.TempData
                };

                filterContext.Result = result;
            }
        }
	}
}

BillsApplication/Views/Shared/NotImplemented.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">OverRiding the where the page shown if an error occures!!</h2>

BillsApplication/Views/Shared/_Create.cshtml
@model BillsApplicationDomain.Bill


    
    <div class="form-horizontal">
        <h4>Bill</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount)
                @Html.ValidationMessageFor(model => model.Amount)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDay, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDay)
                @Html.ValidationMessageFor(model => model.DueDay)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User)
                @Html.ValidationMessageFor(model => model.User)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tag, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Tag)
                @Html.ValidationMessageFor(model => model.Tag)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/Ajax")
}

BillsApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0 maximum-scale=1">
    
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/Ajax")

    <link href=" ~/Content/MobileStyleSheet.css" rel="stylesheet" media="only screen and (max-width: 360px)" />
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div id="menu">
                @Html.Partial("_Menu")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        
        
        <hr />
        <footer>
            @RenderSection("Test", false)

            <!-- The section footer needs to appear on every full page if it is to come out "NOT PARTIALS" if not it will fail Check Index.cshtml-->
            @RenderSection("footer", false)
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BillsApplication/Views/Shared/_Menu.cshtml
@section nav{ <p>This is the menu</p>
   }

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
        <li>@Html.ActionLink("Bills", "Index", "Bill")</li>
    </ul>
    @Html.Partial("_LoginPartial")
</div>